[package]
name = "rpg_game_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
fast_log = {version = "1.5"}
serde = "^1.0.152"
toml = "^0.5.10"
ggez = "0.8.1"
mint = "0.5.9"
